Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -55,12 +55,55 @@ stages:
               resourceGroupName: 'vkak'
               slotName: 'blue'
               package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
-              
-          - task: AzureCLI@2
+          - task: CmdLine@2
             inputs:
-              azureSubscription: 'Free Trial(3e3c63cc-eef2-4386-9f86-ea6a77a47519)'
-              scriptType: 'bash'
-              scriptLocation: 'inlineScript'
-              inlineScript: |
-                echo $(apimupdate)
-                $(apimupdate)
+              script: |
+                # Define the Function App endpoint URL
+                ENDPOINT_URL="https://gs-afa-function-001123-blue.azurewebsites.net/api/endpoints"
+                
+                # Function to perform the health check
+                health_check() {
+                  ALL_PASSED=true
+                
+                  for i in {1..3}; do
+                    echo "Health check attempt $i..."
+                    RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $ENDPOINT_URL)
+                
+                    if [ $RESPONSE -eq 200 ]; then
+                      echo "Health check $i successful: HTTP $RESPONSE"
+                    else
+                      echo "Health check $i failed: HTTP $RESPONSE"
+                      ALL_PASSED=false
+                      break
+                    fi
+                
+                    # Wait for 2 seconds before the next check
+                    sleep 2
+                  done
+                
+                  if $ALL_PASSED; then
+                    echo "All health checks passed!"
+                  else
+                    echo "Health check failed. Exiting with error status."
+                    exit 1
+                  fi
+                }
+                
+                # Call the health check function
+                health_check
+              
+
+- stage: postdeploy
+  displayName: postdeploy
+  jobs:
+  - job: postdeploy
+    displayName: postdeploy
+    steps: 
+      - task: AzureCLI@2
+        inputs:
+          azureSubscription: 'Free Trial(3e3c63cc-eef2-4386-9f86-ea6a77a47519)'
+          scriptType: 'bash'
+          scriptLocation: 'inlineScript'
+          inlineScript: |
+            echo $(apimupdate)
+            $(apimupdate)
